version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15789630
      POSTGRES_DB: flightdb
    ports:
      - "5432:5432"